// Original JPG imports
import careerTransitionsJpg from "@/assets/career-transitions.jpg";
import techCareersJpg from "@/assets/tech-careers.jpg";
import interviewPrepJpg from "@/assets/interview-prep.jpg";
import privateEquityJpg from "@/assets/private-equity.jpg";
import workLifeBalanceJpg from "@/assets/work-life-balance.jpg";
import compensationJpg from "@/assets/compensation.jpg";
import careerDecisionsJpg from "@/assets/career-decisions.jpg";
import networkingJpg from "@/assets/networking.jpg";
import successStoriesJpg from "@/assets/success-stories.jpg";
import consultingSurveyJpg from "@/assets/consulting-survey.jpg";

// WebP imports (generated by scripts/optimize-images.js)
import careerTransitionsWebp from "@/assets/career-transitions.webp";
import techCareersWebp from "@/assets/tech-careers.webp";
import interviewPrepWebp from "@/assets/interview-prep.webp";
import privateEquityWebp from "@/assets/private-equity.webp";
import workLifeBalanceWebp from "@/assets/work-life-balance.webp";
import compensationWebp from "@/assets/compensation.webp";
import careerDecisionsWebp from "@/assets/career-decisions.webp";
import networkingWebp from "@/assets/networking.webp";
import successStoriesWebp from "@/assets/success-stories.webp";
import consultingSurveyWebp from "@/assets/consulting-survey.webp";

// Small JPG imports (400px wide, for responsive srcset)
import careerTransitionsSmJpg from "@/assets/career-transitions-sm.jpg";
import techCareersSmJpg from "@/assets/tech-careers-sm.jpg";
import interviewPrepSmJpg from "@/assets/interview-prep-sm.jpg";
import privateEquitySmJpg from "@/assets/private-equity-sm.jpg";
import workLifeBalanceSmJpg from "@/assets/work-life-balance-sm.jpg";
import compensationSmJpg from "@/assets/compensation-sm.jpg";
import careerDecisionsSmJpg from "@/assets/career-decisions-sm.jpg";
import networkingSmJpg from "@/assets/networking-sm.jpg";
import successStoriesSmJpg from "@/assets/success-stories-sm.jpg";
import consultingSurveySmJpg from "@/assets/consulting-survey-sm.jpg";

// Small WebP imports (400px wide, for responsive srcset)
import careerTransitionsSmWebp from "@/assets/career-transitions-sm.webp";
import techCareersSmWebp from "@/assets/tech-careers-sm.webp";
import interviewPrepSmWebp from "@/assets/interview-prep-sm.webp";
import privateEquitySmWebp from "@/assets/private-equity-sm.webp";
import workLifeBalanceSmWebp from "@/assets/work-life-balance-sm.webp";
import compensationSmWebp from "@/assets/compensation-sm.webp";
import careerDecisionsSmWebp from "@/assets/career-decisions-sm.webp";
import networkingSmWebp from "@/assets/networking-sm.webp";
import successStoriesSmWebp from "@/assets/success-stories-sm.webp";
import consultingSurveySmWebp from "@/assets/consulting-survey-sm.webp";

export interface BlogImage {
  jpg: string;
  webp: string;
  smJpg: string;
  smWebp: string;
}

const careerTransitions: BlogImage = { jpg: careerTransitionsJpg, webp: careerTransitionsWebp, smJpg: careerTransitionsSmJpg, smWebp: careerTransitionsSmWebp };
const techCareers: BlogImage = { jpg: techCareersJpg, webp: techCareersWebp, smJpg: techCareersSmJpg, smWebp: techCareersSmWebp };
const interviewPrep: BlogImage = { jpg: interviewPrepJpg, webp: interviewPrepWebp, smJpg: interviewPrepSmJpg, smWebp: interviewPrepSmWebp };
const privateEquity: BlogImage = { jpg: privateEquityJpg, webp: privateEquityWebp, smJpg: privateEquitySmJpg, smWebp: privateEquitySmWebp };
const workLifeBalance: BlogImage = { jpg: workLifeBalanceJpg, webp: workLifeBalanceWebp, smJpg: workLifeBalanceSmJpg, smWebp: workLifeBalanceSmWebp };
const compensation: BlogImage = { jpg: compensationJpg, webp: compensationWebp, smJpg: compensationSmJpg, smWebp: compensationSmWebp };
const careerDecisions: BlogImage = { jpg: careerDecisionsJpg, webp: careerDecisionsWebp, smJpg: careerDecisionsSmJpg, smWebp: careerDecisionsSmWebp };
const networking: BlogImage = { jpg: networkingJpg, webp: networkingWebp, smJpg: networkingSmJpg, smWebp: networkingSmWebp };
const successStories: BlogImage = { jpg: successStoriesJpg, webp: successStoriesWebp, smJpg: successStoriesSmJpg, smWebp: successStoriesSmWebp };
const consultingSurvey: BlogImage = { jpg: consultingSurveyJpg, webp: consultingSurveyWebp, smJpg: consultingSurveySmJpg, smWebp: consultingSurveySmWebp };

export const categoryImages: Record<string, BlogImage> = {
  "Career Transitions": careerTransitions,
  "Tech Careers": techCareers,
  "Interview Prep": interviewPrep,
  "Private Equity": privateEquity,
  "Work-Life Balance": workLifeBalance,
  "Compensation": compensation,
  "Career Decisions": careerDecisions,
  "Networking": networking,
  "Success Stories": successStories,
};

// Slug-specific images for posts that need custom images
export const slugImages: Record<string, BlogImage> = {
  "consulting-survey-2025": consultingSurvey,
};

export const getImageForSlug = (slug: string): BlogImage | null => {
  return slugImages[slug] || null;
};

export const getImageForCategory = (category: string): BlogImage => {
  return categoryImages[category] || careerTransitions;
};
